package com.example.vimechecker.retrofit

object Transcriptions {
    val localeNames = mapOf("lobby" to "Лобби",
        "luckywars" to "LuckyWars",
        "bw" to "BedWars",
        "prison" to "Prison",
        "eggwars" to "EggWars",
        "sw" to "SkyWars",
        "murder" to "MurderMystery",
        "zombieclaus" to "ZombieClaus",
        "duels" to "Duels",
        "bb" to "BuildBattle",
        "hg" to "HungerGames",
        "speedbuilders" to "SpeedBuilders",
        "mw" to "MobWars",
        "bridge" to "Bridge",
        "kpvp" to "KitPvP",
        "bp" to "BlockParty",
        "ann" to "Annihilation",
        "hide" to "Hide and Seek",
        "tntrun" to "TNTRun",
        "gg" to "GunGame",
        "cp" to "ClashPoint",
        "dr" to "DeathRun",
        "jumpleague" to "JumpLeague",
        "turfwars" to "TurfWars",
        "tnttag" to "TNTTag",
        "teamfortress" to "TeamFortress",
        "sheep" to "Sheep",
        "paintball" to "Paintball",
        "fallguys" to "Fall Guys",
        "bwh" to "BedWarsH",
        "global" to "Глобальные",
        "swt" to "SkyWarsT"
    )
}